dist: trusty
sudo: required
language: node_js
node_js:
  - "8.9"

matrix:
  include:
    - os: linux
      dist: trusty
      before_install: 
      - npm install
      - npm install -g truffle ganache-cli
      - git clone https://github.com/mrsmkl/aragonOS
      - npm install ./aragonOS

script: 
- bash ./travis_test.sh